import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { RequirementAnalysisReport } from '@sprintguard/shared';

function addSection(doc: jsPDF, y: number, title: string, items: string[]): number {
  if (items.length === 0) return y;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 14, y);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  let cursor = y + 5;
  for (const item of items) {
    const lines = doc.splitTextToSize(`- ${item}`, 180);
    if (cursor + lines.length * 4 > 280) {
      doc.addPage();
      cursor = 15;
    }
    doc.text(lines, 14, cursor);
    cursor += lines.length * 4 + 1;
  }
  return cursor + 4;
}

export function exportAnalysisReportToPdf(storyTitle: string, report: RequirementAnalysisReport): void {
  const doc = new jsPDF();
  const { analysis, testCases, coverage } = report;

  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Requirement Intelligence Report', 14, 18);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(storyTitle, 14, 26);
  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text(`Generated by ${report.aiProvider}/${report.model} · v${report.version} · ${new Date(report.createdAt).toLocaleString()}`, 14, 32);
  doc.setTextColor(0);

  let y = 42;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Summary', 14, y);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  const summaryLines = doc.splitTextToSize(analysis.summary, 180);
  doc.text(summaryLines, 14, y + 5);
  y += 5 + summaryLines.length * 4 + 6;

  y = addSection(doc, y, 'Functional Requirements', analysis.functionalRequirements);
  y = addSection(doc, y, 'Business Rules', analysis.businessRules);
  y = addSection(doc, y, 'Risks (Business)', analysis.risks.business);
  y = addSection(doc, y, 'Risks (Technical)', analysis.risks.technical);
  y = addSection(doc, y, 'Edge Cases', analysis.edgeCases);
  y = addSection(doc, y, 'Missing Requirements — Validations', analysis.missingRequirements.validations);

  doc.addPage();
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Coverage', 14, 18);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(
    [
      `Overall: ${coverage.overallPct}%`,
      `Requirement: ${coverage.requirementCoveragePct}%  Business Rule: ${coverage.businessRuleCoveragePct}%`,
      `Acceptance Criteria: ${coverage.acceptanceCriteriaCoveragePct}%  Validation: ${coverage.validationCoveragePct}%`,
      `Edge Case: ${coverage.edgeCaseCoveragePct}%  Risk: ${coverage.riskCoveragePct}%`,
    ],
    14,
    26,
  );

  doc.addPage();
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Test Cases', 14, 18);

  autoTable(doc, {
    startY: 24,
    head: [['ID', 'Title', 'Priority', 'Type', 'Class', 'Pos/Neg', 'Automatable']],
    body: testCases.map((tc) => [
      tc.id,
      tc.title,
      tc.priority,
      tc.testType,
      tc.classification,
      tc.positiveOrNegative,
      tc.automationCandidate ? 'Yes' : 'No',
    ]),
    styles: { fontSize: 8 },
    headStyles: { fillColor: [51, 65, 85] },
  });

  doc.save(`requirement-analysis-${report.storyId}-v${report.version}.pdf`);
}
